# Generated by Django 5.1.5 on 2026-06-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='🔧', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('aula', 'Sala de Aula'), ('laboratorio', 'Laboratorio'), ('reuniao', 'Sala de Reunioes'), ('auditorio', 'Auditorio')], default='aula', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='facilities.building')),
                ('equipment', models.ManyToManyField(blank=True, related_name='rooms', to='facilities.equipment')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'building')},
            },
        ),
    ]
